services:
  - type: web
    name: Izumi-v3
    env: node
    region: frankfurt
    buildCommand: npm install
    startCommand: node index.js
    plan: starter 
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_ID
        value: your_api_key_here
